 SET NAMES utf8 ;
DROP TABLE IF EXISTS `BANCOS`;
 SET character_set_client = utf8mb4 ;
CREATE TABLE `BANCOS` (
  `Numero` int(11) NOT NULL AUTO_INCREMENT,
  `Nombre` varchar(200) NOT NULL,
  PRIMARY KEY (`Numero`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=latin1;
LOCK TABLES `BANCOS` WRITE;
INSERT INTO `BANCOS` VALUES (1,'BANCOLOMBIA'),(2,'BANCO FALABELLA'),(3,'BANCO DE BOGOTA'),(4,'DAVIVIENDA'),(5,'NEQUI'),(6,'BBVA'),(7,'AV VILLAS ');
UNLOCK TABLES;
