 SET NAMES utf8 ;
DROP TABLE IF EXISTS `AFILIADOS`;
 SET character_set_client = utf8mb4 ;
CREATE TABLE `AFILIADOS` (
  `Identificacion` varchar(30) NOT NULL,
  `Primer_Nombre` varchar(50) NOT NULL,
  `Segundo_Nombre` varchar(50) NOT NULL,
  `Primer_Apellido` varchar(50) NOT NULL,
  `Segundo_Apellido` varchar(50) NOT NULL,
  `Tipo_Identificacion` varchar(50) NOT NULL,
  `Fecha_Nacimiento` date NOT NULL,
  `Nacionalidad` varchar(50) NOT NULL,
  `Ciudad` int(11) NOT NULL,
  `Departamento` int(11) NOT NULL,
  `Direccion` varchar(100) NOT NULL,
  `Direccion_Adicional` varchar(200) NOT NULL,
  `Estrato` int(11) NOT NULL,
  `Nivel_Educacion` varchar(80) NOT NULL,
  `Ocupacion` varchar(100) NOT NULL,
  `Rango_Ingresos` int(11) NOT NULL,
  `Forma_Pago` int(11) NOT NULL,
  `Telefono` varchar(20) NOT NULL,
  `Correo` varchar(100) NOT NULL,
  `Direccion_Firma` varchar(200) NOT NULL,
  `Fecha_Firma` date NOT NULL,
  `Horario` time NOT NULL,
  `Estado` varchar(20) NOT NULL,
  `Fecha_Expedicion` date NOT NULL,
  PRIMARY KEY (`Identificacion`),
  KEY `Ciudad` (`Ciudad`),
  KEY `Departamento` (`Departamento`),
  KEY `Rango_Ingresos` (`Rango_Ingresos`),
  KEY `Forma_Pago` (`Forma_Pago`),
  CONSTRAINT `afiliados_ibfk_1` FOREIGN KEY (`Ciudad`) REFERENCES `CIUDADES` (`Codigo`),
  CONSTRAINT `afiliados_ibfk_2` FOREIGN KEY (`Departamento`) REFERENCES `DEPARTAMENTOS` (`Codigo`),
  CONSTRAINT `afiliados_ibfk_3` FOREIGN KEY (`Rango_Ingresos`) REFERENCES `RANGO_INGRESOS` (`Codigo`),
  CONSTRAINT `afiliados_ibfk_4` FOREIGN KEY (`Forma_Pago`) REFERENCES `FORMAS_PAGO` (`Codigo`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
